pub mod format;
pub mod tools;

use std::sync::{Arc, RwLock};

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{ServerCapabilities, ServerInfo};
use rmcp::{tool_handler, ServerHandler};

use crate::live_index::store::LiveIndex;

/// Thread-safe shared handle to the index (re-exported for convenience).
pub type SharedIndex = Arc<RwLock<LiveIndex>>;

/// The MCP server struct.
///
/// Holds a `SharedIndex` and a `ToolRouter` generated by the `#[tool_router]` macro.
/// The `project_name` field is passed through to `format::repo_outline`.
#[derive(Clone)]
pub struct TokenizorServer {
    pub(crate) index: SharedIndex,
    pub(crate) tool_router: ToolRouter<Self>,
    pub(crate) project_name: String,
}

impl TokenizorServer {
    /// Create a new server with the given shared index and project name.
    pub fn new(index: SharedIndex, project_name: String) -> Self {
        Self {
            index,
            tool_router: Self::tool_router(),
            project_name,
        }
    }

    /// Accessor for tests.
    pub fn index(&self) -> &SharedIndex {
        &self.index
    }
}

/// Wire `TokenizorServer` as an MCP `ServerHandler`.
///
/// The `#[tool_handler]` macro delegates tool dispatch to `self.tool_router`
/// and supplies the `call_tool` / `list_tools` implementations automatically.
#[tool_handler(router = self.tool_router)]
impl ServerHandler for TokenizorServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
    }
}
